# 1. Configuración de la Base de Datos
# Reemplaza 'tu_password' por la contraseña de tu MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/negocio_barrio?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración de Hibernate
# 'update' crea las tablas automáticamente si no existen
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 3. Ajustes de Puerto y JSON
server.port=8080
spring.jackson.serialization.write-dates-as-timestamps=false

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG